### ISSUE TITLE
Instruction for Professional theme installation

### ISSUE THREAD

**Issue by bgavran** [katychuang/hakyll-cssgarden#10]
Hi, thank you for a great theme collection!

I was confused by the instructions for a while.
I assume the "Download the files under the theProfessional folder in the hakyll-cssgarden repo"
statement in the [Professional theme ](https://github.com/katychuang/hakyll-cssgarden/blob/master/gallery/theme/2015-11-12-theProfessional.markdown)preview actually refers to the [hakyll-themes](https://github.com/katychuang/hakyll-themes) repo?

Because there is on such directory in the hakyll-cssgarden repo

It took me a while to figure out the css-garden is just a gallery, rather than the source for all the themes.

**Comment by katychuang** [comment]
Hello there, thank you for pointing that out. When I moved the themes to their own repo I forgot to update the instructions. Thanks for reminding me! 

Here's the correct link https://github.com/katychuang/theProfessional-hakyll
